# Generated by Django 5.2.7 on 2025-10-11 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_employee_supplier_stockadjustment_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='expiray_date',
            new_name='expiry_date',
        ),
    ]
