# Generated by Django 5.2.7 on 2025-10-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_qr_code_scanevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='media/qr_codes/'),
        ),
    ]
