# Generated by Django 5.2.7 on 2025-11-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_inventoryalert_systemnotification_productanalytics'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_stock_threshold', models.PositiveIntegerField(default=10, help_text='Alert when stock falls below this number')),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupee (₹)'), ('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)')], default='INR', max_length=3)),
                ('company_name', models.CharField(default='SuperMarket Pro', max_length=200)),
                ('auto_generate_qr', models.BooleanField(default=True, help_text='Auto-generate QR codes for new products')),
                ('qr_format', models.CharField(default='ID,Name,Price', help_text='QR code data format', max_length=100)),
                ('enable_email_alerts', models.BooleanField(default=False)),
                ('alert_check_interval', models.PositiveIntegerField(default=60, help_text='Alert check interval in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
